blueprint:
  name: 🚶‍♂️💡 Bewegungsmelder Außenlicht
  description: >-
    🌙 Intelligente Außenlicht-Steuerung basierend auf Bewegung, Tageszeit & Helligkeitssensor:
    - ⏳ **Vor 22 Uhr** → 🔆 **100% Helligkeit bei Bewegung**, 🌙 **20% bei keiner Bewegung**
    - 🕙 **Nach 22 Uhr** → 🔅 **50% Helligkeit bei Bewegung**, ⛔ **Licht aus ohne Bewegung**
    - 🌅 **30 Min nach Sonnenuntergang** → 🌙 **Licht auf 20%**
    - 🌞 **Tagsüber (ab 30 Min nach Sonnenaufgang)** → 🚫 **Kein Licht durch Bewegung**
  domain: automation
  input:
    motion_sensor:
      name: 🚶‍♂️ Bewegungsmelder
      description: 🎯 Der Bewegungsmelder, der das Licht steuert.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_target:
      name: 💡 Außenlicht
      description: 🏡 Das Licht, das bei Bewegung geschaltet werden soll.
      selector:
        entity:
          domain: light
    illuminance_sensor:
      name: 🌞 Helligkeitssensor
      description: 📊 Sensor für die Umgebungshelligkeit (Lux-Wert).
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    illuminance_threshold:
      name: 🔆 Helligkeitsgrenze (Lux)
      description: ⏳ **Wird das Licht aktiviert, wenn die Umgebungshelligkeit unter diesen Wert fällt?**
      default: 600
      selector:
        number:
          min: 0
          max: 5000
          step: 10
          unit_of_measurement: "lx"


mode: single
trigger:
  - platform: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"
    id: Bewegung_erkannt

  - platform: state
    entity_id: !input motion_sensor
    from: "on"
    to: "off"
    id: Keine_Bewegung
    for:
      hours: 0
      minutes: 0
      seconds: 30

  - platform: sun
    event: sunrise
    offset: "00:30:00"
    id: Tagmodus_an

  - platform: sun
    event: sunset
    offset: "00:30:00"
    id: Nachtmodus_an

  - platform: time
    at: "22:00:00"
    id: Licht_aus_22uhr

action:
  - choose:
      # Tagsüber (30 Min nach Sonnenaufgang) → Licht aus & Bewegung deaktivieren
      - conditions:
          - condition: trigger
            id: Tagmodus_an
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_target

      # Bewegung erkannt → Licht an (nur wenn es dunkel genug ist)
      - conditions:
          - condition: trigger
            id: Bewegung_erkannt
          - condition: numeric_state
            entity_id: !input illuminance_sensor
            below: !input illuminance_threshold
          - condition: sun
            before: sunrise
            before_offset: "-00:30:00"
            after: sunset
            after_offset: "00:30:00"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_target
            data:
              brightness_pct: 100

      - conditions:
          - condition: trigger
            id: Bewegung_erkannt
          - condition: numeric_state
            entity_id: !input illuminance_sensor
            below: !input illuminance_threshold
          - condition: time
            after: "22:00:00"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_target
            data:
              brightness_pct: 50

      # Keine Bewegung mehr → Licht auf 20% (vor 22 Uhr)
      - conditions:
          - condition: trigger
            id: Keine_Bewegung
          - condition: numeric_state
            entity_id: !input illuminance_sensor
            below: !input illuminance_threshold
          - condition: sun
            after: sunset
            after_offset: "00:30:00"
          - condition: time
            before: "22:00:00"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_target
            data:
              brightness_pct: 20

      # Keine Bewegung mehr → Licht aus nach 22 Uhr
      - conditions:
          - condition: trigger
            id: Keine_Bewegung
          - condition: time
            after: "22:00:00"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_target

      # 30 Min nach Sonnenuntergang → Licht auf 20%, falls es vorher aus war
      - conditions:
          - condition: trigger
            id: Nachtmodus_an
          - condition: numeric_state
            entity_id: !input illuminance_sensor
            below: !input illuminance_threshold
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_target
            data:
              brightness_pct: 20
